PERFORM zf_corrige_campo_desc_confir.


FORM zf_corrige_campo_desc_confir.

T_SAIDA_AUX TYPE TABLE OF Y_SAIDA.

T_SAIDA_AUX[] = CORRESPONDING #( T_SAIDA[] ).
REFRESH T_SAIDA.

LOOP A T_SAIDA_AUX INTO DATA(W_SAIDA_AUX).

 SELECT MAKTX
 FROM MAKT
 INTO @DATA(V_MAKTX)
 WHERE MATNR EQ ITEM_MATNR AND
       SPRAS EQ SY-LANGU.

 CLEAR W_SAIDA_AUX-DESC_CONFIR.
 W_SAIDA_AUX-DESC_CONFIR = V_MAKTX. 

 APPEND W_SAIDA_AUX TO T_SAIDA.
 CLEAR: V_MAKTX,
        W_SAIDA_AUX.
ENDLOOP.

ENDFORM.
